edgar/urls.py
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path("finance_data/", include("finance_data.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("foo_app/", include("foo_app.urls")),
]

finance_data/urls.py
from django.urls import path

from . import views

# urlpatterns = [
#     path("", views.index, name="index"),
#     path("foo", views.foo, name="foo"),
#     ]
app_name = "finance_data"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/detail/", views.detail_question, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

foo_app/urls.py
from django.urls import path


from . import views

app_name = "foo_app"
urlpatterns = [
    path("", views.index, name="index"),
]

finance_data/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    
def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

foo_app/models.py
from django.db import models

# Create your models here.

finance_data/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render

from django.urls import reverse
from django.views import generic
from .models import Choice, Question
from django.utils import timezone

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "finance_data/index.html", context)

def detail_question(request, question_id):
    latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
    question = get_object_or_404(Question, id=question_id)
    return render(request, "finance_data/detail.html", {"question": question, "latest_question_list": latest_question_list})

def results(request, question_id):
    latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "finance_data/results.html", {"question": question, "latest_question_list":latest_question_list})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "finance_data/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("finance_data:results", args=(question.id,)))

foo_app/views.py
from django.shortcuts import render
from finance_data.models import Question, Choice


# Create your views here.
def index(request):
   query = request.GET.get("q","")
   if query is not None:
      question_results = Question.objects.filter(question_text__icontains=query)
      choice_results = Choice.objects.filter(choice_text__icontains=query)
   print(locals())
   return render(request, "foo_app/index.html", locals())
      
  

   
 

finance_data/templates/finance_data/base.html
<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
      {% comment %}
      {% load static %}
      <link rel="stylesheet" href="{% static 'finance_data/style.css' %}">
      {% endcomment %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">EDGAR</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/finance_data">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/admin">Admin</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Questions
              </a>
              <ul class="dropdown-menu">
                  {% if latest_question_list %}
                    {% for question in latest_question_list %}
                        <li>
                            <a class="dropdown-item" href="{% url 'finance_data:detail' question.id %}">{{ question.question_text }}</a>
                        </li>
                    {% endfor %}
                  {% else %}
                    <li>No polls are available.</li>
                  {% endif %}
              </ul>
            </li>  
          </ul>
        </div>
      </div>
    </nav>
                  
    <main class="container">
      {% block content %}
       <h1> hello from index</h1>
      {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

finance_data/templates/finance_data/detail.html
{% extends "finance_data/base.html" %}

{% block content %}
    <form action="{% url 'finance_data:vote' question.id %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                {% for choice in question.choice_set.all %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                        <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                    </div> 
                {% endfor %}
                <input type="submit" value="Vote">
        </fieldset>
    </form>
{%endblock%}

finance_data/templates/finance_data/index.html
{% extends "finance_data/base.html" %}
{% block content %}
    <h1> Hello Home</h1>



{% endblock %}

finance_data/templates/finance_data/results.html
{% extends "finance_data/base.html" %}
{% block content %}
    <legend><h1>{{ question.question_text }}</h1></legend>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'finance_data:detail' question.id %}">Vote again?</a><br>
{% endblock %}

finance_data/templates/financial_data/finance.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'finance_data:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

foo_app/templates/foo_app/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">    
      
      <style>
              footer{
                display: flex;
                justify-content: space-between;
                margin-top: 4rem;
                border-top: gray solid 1px;
                padding-top: 0.5rem;
                padding: 2rem;
                padding-top: 2rem;
                padding-top: 0.5rem;
              }

             footer ul{
                  list-style: none;
                  display: flex;
                }
              
             footer li{
              margin-left: 0.5rem; 

             }
             @media (max-width: 768px) {
              footer{
                flex-direction: column-reverse;
              }
              footer ul{
                flex-direction: column;
                padding-left: 0;
              }
              footer li{
                margin-left: 0;
              }
            }
            
      </style>
  
  
  
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">DIANA</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/page1.html">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                </ul>
                <form class="d-flex" role="search" method="GET">
                  <input class="form-control me-2" value="{{query}}" autofocus="" name="q" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>

          {% if query %}

            <p>You search for "{{query}}"</p>

            <h2>Question Results:</h2>
            <ol>
              {% for question in question_results %}
                <li><a href= "{% url 'finance_data:detail' question.id %}">{{question.question_text | capfirst}}</a></li>
              {% empty %}
                <li>Sorry no question result for your query 😞</li>
              {% endfor %}
            </ol>
            

            <h2>Choice Results:</h2>
            <ol>
              {% for choice in choice_results %}
                <li>{{choice.choice_text}} <span class="badge text-bg-primary">{{choice.votes}} votes</span>
                  Question:<a href="{% url 'finance_data:detail' choice.question.id %}"> {{choice.question.question_text | capfirst  }}</a> (published {{choice.question.pub_date | timesince}} ago)</li>
              {% empty %}
                <li> Sorry no choice result for your query 😞</li>
              {% endfor %}
            </ol>

          {% endif %}


        <footer>
            <div class="footer">
              <p>© 2023 Company, Inc</p>
            </div>
            <div class="logo">
              <p>😁</p>
            </div>
            <ul>
              <li>Home</li>
              <li>Features</li>
              <li>FAQs</li>
              <li>About Us</li>
              <li>Contact Us</li>
            </ul>
        </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    </body>
</html>

foo_app/templates/foo_app/page1.html
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">    
      
    </head>
<body>
<p>hi</p>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>